# Generated by Django 2.1.3 on 2018-12-08 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category_id',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_id',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Venue'),
        ),
    ]
